name: Build and Push Packages

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Install Dependencies
        run: pnpm install

      - name: Check Changed Packages
        id: changes
        run: |
          npx changeset status --json > changes.json
          echo "::set-output name=changed_packages::$(node -p \"require('./changes.json').changes.map(change => change.commit).join(' ')\" | xargs)"

      - name: Build and Push Packages
        run: |
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > $package/.npmrc
          for commit in ${{ steps.changes.outputs.changed_packages }}
          do
            npx changeset publish --commit $commit
            cd $(npx changeset version $commit --output)
            npm publish --access public
            cd ..
          done
